### ISSUE TITLE
About finishing this

### ISSUE THREAD

**Issue by arthurwolf** [akhilkedia/lolex-queue#1]
I really need a finished version of this. I could pay for the work. Anyone interested?
wolf.arthur@gmail.com

**Comment by akhilkedia** [comment]
Unfortunately I am tied up in other work at the moment. But feel free to base your code off of mine.
Disclaimer - I had not updated this to work with all of lolex's APIs, only the ones I had used. You can see the diffs to check.

**Comment by arthurwolf** [comment]
Thanks a ton for the answer!

I'm trying to get it to work (setTimeout / tick() ) but it won't do anything.

I'm trying to get it to work, but I'm a bit lost on one thing:

        if (typeof timer.interval === "number") {
            // TODO:
            clock.timerq.pop();
            // clock.timers[timer.id].callAt += timer.interval;
            clock.timersq.push(timer);
        } else {
            // delete clock.timers[timer.id];
            clock.timersq.pop();
        }

why the first pop() there, what is that doing/what's the logic, if you remember at all?

**Comment by arthurwolf** [comment]
fyi, I got it to work, it was quite a bit of work, but now my code is 10x faster.
my plan long-term is to make a PR gainst lolex with some more changes, but it's going to be some more work
thanks for the help!
